name: 主页

on:
  push:
    branches:
      - src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_SCRIPT: npm i && npm run build
        BUILD_DIR: .vuepress/dist/
        CNAME: viva-la-vita.org
