name: Home Page

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.PAT }}
        BUILD_SCRIPT: npm i && npm run build
        BUILD_DIR: .vuepress/dist/
        CNAME: https://viva-la-vita.org
